### PR TITLE
Scoreboard

### PR DESCRIPTION
**Pull request by p-kuen**
Just a little scoreboard I made
A few things should be improved, like the rank name.
I just wanted to give it to you because it may helps you :)

### CODE REVIEW

**Comment by monkstick-git** [comment]
when I spawn a prop, server crashes with no error, also the owner rank is "sv_owner" instead of just owner.

**Comment by Mors-Quaedam** [comment]
It shows as srv_owner, when I am on my computer later I will fix this up.

**Comment by monkstick-git** [comment]
This is the offending line thats causing a crash.

```
timer.Simple(1, function()
    PLUGIN.GetCount = exsto.Registry.Player.GetCount
    function exsto.Registry.Player:GetCount(limit, minus)
        if limit == "props" then
            timer.Simple(.1, function() PLUGIN.GetCount(self, limit, 0) end)
        end
        return PLUGIN.GetCount(self, limit, minus) <<<<<<<<<<<<<<<<<<<<<<<<<<<
    end
end)
```

One other small gripe, the server title doesn't get scaled down to fit in the box, so the name just spills over out of the box.

Oh, and can you make it sort by rank, or something similar?  everyone just seems to be thrown together in the same table.

**Comment by nexbr** [comment]
I Ported SUI Scoreboard for Exsto.

http://steamcommunity.com/sharedfiles/filedetails/?id=160121673 or https://github.com/nexbr/sui-scoreboard-for-Exsto, Wich you prefanatic don't need to merge to Exsto.

Suicidal Banana Liked :-)

**Pull request closed without merging**
